site_name: AUV Control Board
theme:
    name: readthedocs
    highlightjs: true
markdown_extensions:
  - attr_list
nav:
  - Home: index.md
  - Hardware:
    - Version 1: hardware/v1.md
    - Version 2: hardware/v2.md
  - Firmware:
    - Overview: firmware/overview.md
    - Build and Flash: firmware/build.md
    - 6DOF Math: firmware/math.md
    - Firmware Development: firmware/developing.md
  - User Guide:
    - Coming Eventually: none.md