site_name: AUV Control Board
repo_url: https://github.com/MB3hel/AUVControlBoard
edit_uri: blob/main/docs/docs
site_url: !ENV [SITE_URL, "https://mb3hel.github.io/AUVControlBoard/"]
use_directory_urls: !ENV [DIR_URLS, true]
theme:
  name: readthedocs
  highlightjs: true
markdown_extensions:
  - attr_list
  - mdx_math:
      enable_dollar_delimiter: True
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
nav:
  - Home: index.md
  - Hardware:
    - Version 1: hardware/v1.md
    - Version 2: hardware/v2.md
    - Off-Board Sensors: hardware/sensors.md
  - User Guide:
    - Preparing a Control Board: user_guide/preparing_board.md
    - Using Control board: user_guide/general_use.md
    - Using the Simulator: user_guide/simulator.md
    - Communication Protocol: user_guide/comm_protocol.md
    - Messages: user_guide/messages.md
  - Developers:
    - Overview: firmware/overview.md
    - Build and Flash: firmware/build.md
    - Math: firmware/math.md
    - Firmware Development: firmware/developing.md