site_name: AUV Control Board
repo_url: https://github.com/MB3hel/AUVControlBoard
edit_uri: blob/main/docs/docs
site_url: !ENV [SITE_URL, "https://mb3hel.github.io/AUVControlBoard/"]
use_directory_urls: !ENV [DIR_URLS, true]
theme:
  name: readthedocs
  highlightjs: true
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - User Guide:
    - Preparing a Control Board: user_guide/preparing_board.md
    - Using Control Board: user_guide/general_use.md
    - Using the Python Interface: user_guide/pythoniface.md
    - Using SimCB and Simulator: user_guide/simcb_simulator.md
    - Sensor Calibration: user_guide/calibration.md
    - Communication Protocol: user_guide/comm_protocol.md
    - Messages: user_guide/messages.md
  - Hardware:
    - Version 1: hardware/v1.md
    - Version 2: hardware/v2.md
    - Off-Board Sensors: hardware/sensors.md
  - Developers:
    - Firmware Overview: devs/overview.md
    - Firmware Details: devs/details.md
    - Simulation Support: devs/simulation.md
    - Build and Flash Firmware: devs/build.md
    - Build and Run SimCB: devs/buildsimcb.md
    - Interface Scripts: devs/pythoniface.md
    - Development Workflows: devs/developing.md
    - Math: devs/math.md
