name: Build Release Package
on:
  push:
    branches:
      - 'feature/simcb'
jobs:
  BasePackage:
    runs-on: ubuntu-latest
    name: base
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y ninja-build cmake build-essential gcc-arm-none-eabi
      - working-directory: ./docs
        run: python3 -m pip install -r requirements.txt
      - working-directory: ./package
        run: ./pack_clean.sh
      - working-directory: ./package
        run: ./pack_setup.sh
      - working-directory: ./package
        run: ./pack_firmware.sh
      - working-directory: ./package
        run: ./pack_iface.sh
      - working-directory: ./package
        run: ./pack_docs.sh
      - uses: actions/upload-artifact@v3
        with:
          name: base
          path: ./package/pack/*
          retention-days: 1
  SimCBLinux:
    runs-on: ubuntu-latest
    name: simcb-linux
    steps:
      - uses: actions/checkout@v4
      - working-directory: ./package
        run: ./pack_simcb_linux.sh
      - uses: actions/upload-artifact@v3
        with:
          name: simcb-linux
          path: ./package/pack/*
          retention-days: 1
  SimCBMacOS:
    runs-on: macos-latest
    name: simcb-macos
    steps:
      - uses: actions/checkout@v4
      - run: brew install cmake ninja
      - working-directory: ./package
        run: ./pack_simcb_macos.sh
      - uses: actions/upload-artifact@v3
        with:
          name: simcb-macos
          path: ./package/pack/*
          retention-days: 1
  SimCBWindows:
    runs-on: windows-latest
    name: simcb-win
    steps:
      - uses: actions/checkout@v4
      - run: choco install cmake ninja
      - working-directory: ./package
        run: ./pack_simcb_win.cmd
      - uses: actions/upload-artifact@v3
        with:
          name: simcb-windows
          path: ./package/pack/*
          retention-days: 1
  CombinePackage:
    runs-on: ubuntu-latest
    needs: [simcb-win, simcb-macos, simcb-linux, base]
    name: combine-package
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: base
      - uses: actions/download-artifact@v3
        with:
          name: simcb-linux
      - uses: actions/download-artifact@v3
        with:
          name: simcb-macos
      - uses: actions/download-artifact@v3
        with:
          name: simcb-windows
      - run: mkdir pack
      - run: unzip base.zip -d pack/
      - run: unzip simcb-linux.zip -d pack/
      - run: unzip simcb-macos.zip -d pack/
      - run: unzip simcb-windows.zip -d pack/
      - run: chmod +x pack/simcb/linux-amd64/SimCB
      - run: chmod +x pack/simcb/linux-amd64/SimCB.run
      - run: chmod +x pack/simcb/macos-intel/SimCB
      - working-directory: pack
        run: zip ../pack.zip ./*
      - uses: actions/upload-artifact@v3
        with:
          name: full-package
          path: pack.zip
          retention-days: 1
